{{- $clientPortSeed := .Release.Name }}
{{- $adminPortSeed := printf "adm-%s" .Release.Name -}}
{{- $clientPortHash := sha256sum $clientPortSeed | trunc 8 | atoi -}}
{{- $clientPort := add 30000 (mod $clientPortHash 10000) -}}
{{- $adminPortHash := sha256sum $adminPortSeed | trunc 8 | atoi -}}
{{- $adminPort := add 30000 (mod $adminPortHash 10000) -}}
{{- $prefix := sha256sum .Release.Name | trunc 10 -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ include "chart.fullname" . }}
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "chart.fullname" . }}
      {{- include "chart.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "chart.fullname" . }}
        {{- include "chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: {{ include "chart.fullname" . }}-init
          image: bash:5-alpine3.21
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/bash", "/opt/init/init.sh"]
          env:
            - name: CLIENT_PORT
              value: "{{ $clientPort }}"
            - name: API_PORT
              value: "{{ $adminPort }}"
            - name: SB_API_PREFIX
              value: "{{ $prefix }}"
          volumeMounts:
            - name: {{ include "chart.fullname" . }}-data
              mountPath: /opt/outline
            - name: {{ include "chart.fullname" . }}-init
              mountPath: /opt/init
      containers:
        - name: {{ include "chart.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ trunc 7 .Release.Name }}-clt-tcp
              containerPort: {{ $clientPort }}
              protocol: TCP
            - name: {{ trunc 7 .Release.Name }}-clt-udp
              containerPort: {{ $clientPort }}
              protocol: UDP
            - name: {{ trunc 7 .Release.Name }}-adm-tcp
              containerPort: {{ $adminPort }}
              protocol: TCP
          env:
            - name: SB_STATE_DIR
              value: "/opt/outline/persisted-state"
            - name: SB_API_PORT
              value: "{{ $adminPort }}"
            - name: SB_API_PREFIX
              value: "{{ $prefix }}"
            - name: SB_CERTIFICATE_FILE
              value: "/opt/outline/persisted-state/shadowbox-selfsigned.crt"
            - name: SB_PRIVATE_KEY_FILE
              value: "/opt/outline/persisted-state/shadowbox-selfsigned.key"
            - name: SB_METRICS_URL
              value: ""
            - name: SB_DEFAULT_SERVER_NAME
              value: ""
          volumeMounts:
            - name: {{ .Release.Name }}-data
              mountPath: /opt/outline
      volumes:
        - name: {{ .Release.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        - name: {{ .Release.Name }}-init
          configMap:
            name: init-scripts
            defaultMode: 0755
