{{- $clientPortSeed := .Release.Name }}
{{- $adminPortSeed := printf "adm-%s" .Release.Name -}}
{{- $clientPortHash := sha256sum $clientPortSeed | trunc 8 | atoi -}}
{{- $clientPort := add 30000 (mod $clientPortHash 10000) -}}
{{- $adminPortHash := sha256sum $adminPortSeed | trunc 8 | atoi -}}
{{- $adminPort := add 30000 (mod $adminPortHash 10000) -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ include "chart.fullname" . }}
  ports:
    - protocol: TCP
      name: {{ include "chart.fullname" . }}-tcp
      port: {{ $clientPort }}
      targetPort: {{ trunc 7 .Release.Name }}-clt-tcp
    - protocol: UDP
      name: {{ include "chart.fullname" . }}-udp
      port: {{ $clientPort }}
      targetPort: {{ trunc 7 .Release.Name }}-clt-udp
    - protocol: TCP
      name: {{ include "chart.fullname" . }}-management-tcp
      port: {{ $adminPort }}
      targetPort: {{ trunc 7 .Release.Name }}-adm-tcp
  externalTrafficPolicy: Local
  type: {{ .Values.service.type }}
